"""Add ON DELETE CASCADE / SET NULL to thinker-related FK constraints.

Revision ID: 005_fk_ondelete
Revises: phase13_cataloged_idx
Create Date: 2026-04-16

Source: DATA-REVIEW C2 -- zero `ondelete` specifications existed anywhere in
the schema, so deleting a `Thinker` raised FK violations from every junction
and side-table referencing it.

This migration drops and recreates the relevant FKs with explicit ON DELETE:

- CASCADE for junction/ownership tables that have no meaning without the
  parent row: source_thinkers, content_thinkers, thinker_profiles,
  thinker_metrics, thinker_categories, source_categories.
- SET NULL for candidate_thinkers.thinker_id, which preserves candidate
  review history even if the promoted thinker is later deleted.

All FK constraint names follow Postgres's default `<table>_<column>_fkey`
convention from the initial autogenerated schema.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "005_fk_ondelete"
down_revision: Union[str, Sequence[str], None] = "phase13_cataloged_idx"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (constraint_name, table, columns, ref_table, ref_columns, ondelete)
_CASCADE_FKS = [
    (
        "source_thinkers_source_id_fkey",
        "source_thinkers",
        ["source_id"],
        "sources",
        ["id"],
    ),
    (
        "source_thinkers_thinker_id_fkey",
        "source_thinkers",
        ["thinker_id"],
        "thinkers",
        ["id"],
    ),
    (
        "content_thinkers_content_id_fkey",
        "content_thinkers",
        ["content_id"],
        "content",
        ["id"],
    ),
    (
        "content_thinkers_thinker_id_fkey",
        "content_thinkers",
        ["thinker_id"],
        "thinkers",
        ["id"],
    ),
    (
        "thinker_profiles_thinker_id_fkey",
        "thinker_profiles",
        ["thinker_id"],
        "thinkers",
        ["id"],
    ),
    (
        "thinker_metrics_thinker_id_fkey",
        "thinker_metrics",
        ["thinker_id"],
        "thinkers",
        ["id"],
    ),
    (
        "thinker_categories_thinker_id_fkey",
        "thinker_categories",
        ["thinker_id"],
        "thinkers",
        ["id"],
    ),
    (
        "thinker_categories_category_id_fkey",
        "thinker_categories",
        ["category_id"],
        "categories",
        ["id"],
    ),
    (
        "source_categories_source_id_fkey",
        "source_categories",
        ["source_id"],
        "sources",
        ["id"],
    ),
    (
        "source_categories_category_id_fkey",
        "source_categories",
        ["category_id"],
        "categories",
        ["id"],
    ),
]

_SET_NULL_FKS = [
    (
        "candidate_thinkers_thinker_id_fkey",
        "candidate_thinkers",
        ["thinker_id"],
        "thinkers",
        ["id"],
    ),
]


def upgrade() -> None:
    """Drop and recreate FKs with CASCADE / SET NULL semantics."""
    for name, table, cols, ref_table, ref_cols in _CASCADE_FKS:
        op.drop_constraint(name, table, type_="foreignkey")
        op.create_foreign_key(
            name,
            table,
            ref_table,
            cols,
            ref_cols,
            ondelete="CASCADE",
        )
    for name, table, cols, ref_table, ref_cols in _SET_NULL_FKS:
        op.drop_constraint(name, table, type_="foreignkey")
        op.create_foreign_key(
            name,
            table,
            ref_table,
            cols,
            ref_cols,
            ondelete="SET NULL",
        )


def downgrade() -> None:
    """Revert FKs to NO ACTION (the Postgres default)."""
    for name, table, cols, ref_table, ref_cols in _CASCADE_FKS + _SET_NULL_FKS:
        op.drop_constraint(name, table, type_="foreignkey")
        op.create_foreign_key(name, table, ref_table, cols, ref_cols)
