"""Drop deprecated Source.thinker_id and Content.source_owner_id columns.

Revision ID: 014_drop_deprecated_cols
Revises: 013_latest_pub_and_description
Create Date: 2026-04-17

Source: DATA-REVIEW M5 + L4.

After PR #17 (sources-first-class) the many-to-many thinker<->source
relationship moved onto the ``source_thinkers`` junction table, and
after Phase 13 (PR #18) content attribution moved onto
``content_thinkers``. Both original FK columns -- ``sources.thinker_id``
and ``content.source_owner_id`` -- were made nullable in migration 004
and have been untouched by production writes since:

* ``fetch_podcast_feed`` and ``fetch_youtube_channel`` explicitly pass
  ``source_owner_id=None`` on every new ``Content`` row (Phase 13).
* ``discover_guests_podcastindex`` writes to ``source_thinkers`` instead
  of ``Source.thinker_id`` (PR #17).
* Model-level event listener added in PR #45 (DATA M2) emits a
  ``DeprecationWarning`` on any remaining writes to ``Source.thinker_id``
  -- no such warnings have surfaced in staging.

The columns are carrying rot: they still appear in ``ContentResponse``
API schemas, admin templates, and the agent's DATABASE_SCHEMA docstring.
Dropping them removes the ambiguity ("which column is authoritative?")
and shrinks the content table by one nullable UUID per row.

**Data preservation:** the data these columns once held was copied into
``source_thinkers`` by migration 004 step 6 (with ``ON CONFLICT DO
NOTHING`` so re-running is idempotent). ``content_thinkers`` is
populated by the Phase 13 ``tag_content_thinkers`` / scan pipeline.
Nothing in this migration is destructive of thinker linkage data --
only the deprecated denormalized pointers are dropped.

**Downgrade caveat:** the ``downgrade`` path re-creates the columns as
nullable. It does NOT restore the original values (they were never
deleted from ``source_thinkers`` / ``content_thinkers`` but there's no
1:1 inverse for content that now has multiple thinkers in its junction).
If a rollback is required, run the junction-read path instead.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "014_drop_deprecated_cols"
down_revision: str | Sequence[str] | None = "013_latest_pub_and_description"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Drop FK indexes first (created in migration 009). The DROP COLUMN
    # would cascade these automatically, but dropping them explicitly
    # keeps the migration symmetric with the downgrade path and avoids
    # relying on CASCADE semantics.
    op.drop_index("ix_content_source_owner_id", table_name="content")
    op.drop_index("ix_sources_thinker_id", table_name="sources")

    # Drop FK constraints (standard <table>_<column>_fkey naming from the
    # initial autogenerated schema in 92ce969b2ede).
    op.drop_constraint("content_source_owner_id_fkey", "content", type_="foreignkey")
    op.drop_constraint("sources_thinker_id_fkey", "sources", type_="foreignkey")

    # Drop the columns themselves.
    op.drop_column("content", "source_owner_id")
    op.drop_column("sources", "thinker_id")


def downgrade() -> None:
    # Re-add columns as nullable (matches the post-004 shape). Data is
    # NOT restored — see module docstring.
    op.add_column(
        "sources",
        sa.Column("thinker_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "content",
        sa.Column("source_owner_id", sa.Uuid(), nullable=True),
    )

    # Recreate FKs (no ondelete — matches original schema).
    op.create_foreign_key(
        "sources_thinker_id_fkey",
        "sources",
        "thinkers",
        ["thinker_id"],
        ["id"],
    )
    op.create_foreign_key(
        "content_source_owner_id_fkey",
        "content",
        "thinkers",
        ["source_owner_id"],
        ["id"],
    )

    # Recreate FK indexes (matches migration 009).
    op.create_index("ix_sources_thinker_id", "sources", ["thinker_id"], unique=False)
    op.create_index(
        "ix_content_source_owner_id",
        "content",
        ["source_owner_id"],
        unique=False,
    )
