"""initial schema

Revision ID: 92ce969b2ede
Revises:
Create Date: 2026-03-08 18:02:10.217168

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "92ce969b2ede"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("api_name", sa.Text(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("call_count", sa.Integer(), nullable=False),
        sa.Column("units_consumed", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_api_usage_timeseries", "api_usage", ["api_name", "period_start"], unique=False)
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "llm_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("review_type", sa.Text(), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column(
            "context_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("prompt_used", sa.Text(), nullable=False),
        sa.Column("llm_response", sa.Text(), nullable=True),
        sa.Column("decision", sa.Text(), nullable=True),
        sa.Column("decision_reasoning", sa.Text(), nullable=True),
        sa.Column("modifications", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("flagged_items", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("overridden_by", sa.Text(), nullable=True),
        sa.Column("overridden_at", sa.DateTime(), nullable=True),
        sa.Column("override_reasoning", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rate_limit_usage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("api_name", sa.Text(), nullable=False),
        sa.Column("worker_id", sa.Text(), nullable=False),
        sa.Column("called_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rate_limit_usage_window", "rate_limit_usage", ["api_name", "called_at"], unique=False)
    op.create_table(
        "system_config",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("set_by", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "thinkers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.Column("primary_affiliation", sa.Text(), nullable=True),
        sa.Column("twitter_handle", sa.Text(), nullable=True),
        sa.Column("wikipedia_url", sa.Text(), nullable=True),
        sa.Column("personal_site", sa.Text(), nullable=True),
        sa.Column("approval_status", sa.Text(), server_default="pending_llm", nullable=False),
        sa.Column("approved_backfill_days", sa.Integer(), nullable=True),
        sa.Column("approved_source_types", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("added_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("last_refreshed", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "candidate_thinkers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("appearance_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("sample_urls", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("inferred_categories", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("suggested_twitter", sa.Text(), nullable=True),
        sa.Column("suggested_youtube", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending_llm", nullable=False),
        sa.Column("llm_review_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_by", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("thinker_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["llm_review_id"],
            ["llm_reviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thinker_id"],
            ["thinkers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.Text(), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default=sa.text("5"), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), server_default=sa.text("3"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_category", sa.Text(), nullable=True),
        sa.Column("last_error_at", sa.DateTime(), nullable=True),
        sa.Column("worker_id", sa.Text(), nullable=True),
        sa.Column("llm_review_id", sa.Uuid(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["llm_review_id"],
            ["llm_reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_claim", "jobs", ["status", "priority", "scheduled_at"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("thinker_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("approval_status", sa.Text(), server_default="pending_llm", nullable=False),
        sa.Column("approved_backfill_days", sa.Integer(), nullable=True),
        sa.Column("backfill_complete", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("refresh_interval_hours", sa.Integer(), nullable=True),
        sa.Column("last_fetched", sa.DateTime(), nullable=True),
        sa.Column("item_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("error_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["thinker_id"],
            ["thinkers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "thinker_categories",
        sa.Column("thinker_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("relevance", sa.SmallInteger(), nullable=False),
        sa.Column("added_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thinker_id"],
            ["thinkers.id"],
        ),
        sa.PrimaryKeyConstraint("thinker_id", "category_id"),
    )
    op.create_table(
        "thinker_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("thinker_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("handle", sa.Text(), nullable=False),
        sa.Column("followers", sa.BigInteger(), nullable=False),
        sa.Column("avg_views", sa.BigInteger(), nullable=False),
        sa.Column("post_count", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("snapshotted_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["thinker_id"],
            ["thinkers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "thinker_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("thinker_id", sa.Uuid(), nullable=False),
        sa.Column(
            "education", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column(
            "positions_held",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "notable_works",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "awards", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["thinker_id"],
            ["thinkers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_owner_id", sa.Uuid(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("content_fingerprint", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("show_name", sa.Text(), nullable=True),
        sa.Column("host_name", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("transcription_method", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("discovered_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_owner_id"],
            ["thinkers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_url"),
        sa.UniqueConstraint("content_fingerprint"),
    )
    op.create_table(
        "content_thinkers",
        sa.Column("content_id", sa.Uuid(), nullable=False),
        sa.Column("thinker_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("confidence", sa.SmallInteger(), nullable=False),
        sa.Column("added_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["content.id"],
        ),
        sa.ForeignKeyConstraint(
            ["thinker_id"],
            ["thinkers.id"],
        ),
        sa.PrimaryKeyConstraint("content_id", "thinker_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("content_thinkers")
    op.drop_table("content")
    op.drop_table("thinker_profiles")
    op.drop_table("thinker_metrics")
    op.drop_table("thinker_categories")
    op.drop_table("sources")
    op.drop_index("ix_jobs_claim", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("candidate_thinkers")
    op.drop_table("thinkers")
    op.drop_table("system_config")
    op.drop_index("ix_rate_limit_usage_window", table_name="rate_limit_usage")
    op.drop_table("rate_limit_usage")
    op.drop_table("llm_reviews")
    op.drop_table("categories")
    op.drop_index("ix_api_usage_timeseries", table_name="api_usage")
    op.drop_table("api_usage")
    # ### end Alembic commands ###
